/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.gui.responsableagence;

import edu.esprit.DAO.classes.ClientDAO;
import edu.esprit.DAO.classes.TrajetDAO;
import edu.esprit.adapters.ConsulterTrajets;
import edu.esprit.entities.Client;
import edu.esprit.entities.Trajet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Houssem
 */
public class GestionTrajet extends javax.swing.JFrame {

    /**
     * Creates new form GestionTrajet
     */
    private List<Trajet> listeTrajets;
    
    public GestionTrajet() {
        initComponents();
        listeTrajets=TrajetDAO.getInstance().DisplayAllTrajets();
        jTable1.setModel(new ConsulterTrajets(listeTrajets));
    }

    
    private void refresh(){
        listeTrajets=TrajetDAO.getInstance().DisplayAllTrajets();

        jTable1.setModel(new ConsulterTrajets(listeTrajets));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        retourButton = new javax.swing.JButton();
        ajouterButton = new javax.swing.JButton();
        supprimerButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        adresseDep = new javax.swing.JTextField();
        adresseDest = new javax.swing.JTextField();
        modifierButton = new javax.swing.JButton();
        rechercheButton = new javax.swing.JButton();
        critereRecherche = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        recherche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        retourButton.setText("Retour");
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        ajouterButton.setText("Ajouter");
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        supprimerButton.setText("Supprimer");
        supprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        modifierButton.setText("Modifier");
        modifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButtonActionPerformed(evt);
            }
        });

        rechercheButton.setText("Recherche");
        rechercheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheButtonActionPerformed(evt);
            }
        });

        critereRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adresse Depart", "Adresse Destination" }));

        jLabel1.setText("Adresse Depart");

        jLabel2.setText("Adresse Destination");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(retourButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton)
                        .addGap(18, 18, 18)
                        .addComponent(modifierButton)
                        .addGap(11, 11, 11)
                        .addComponent(supprimerButton)
                        .addGap(18, 18, 18)
                        .addComponent(ajouterButton)
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adresseDep)
                    .addComponent(adresseDest, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(critereRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(rechercheButton)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheButton)
                    .addComponent(critereRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterButton)
                    .addComponent(supprimerButton)
                    .addComponent(refreshButton)
                    .addComponent(retourButton)
                    .addComponent(resetButton)
                    .addComponent(modifierButton))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        adresseDep.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        adresseDest.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        
        switch (critereRecherche.getSelectedItem()+"") {
                case "Adresse Depart":
                    recherche.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
                    break;
                case "Adresse Destination":
                    recherche.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
                    break;
                default:
                    adresseDep.setText("Erreur");
                    break;
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        AccueilRespAgence.getAccueilGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourButtonActionPerformed

    private void supprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerButtonActionPerformed
        try {
            TrajetDAO.getInstance().deleteTrajet(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner une ligne" );
        }
    }//GEN-LAST:event_supprimerButtonActionPerformed

    private void rechercheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheButtonActionPerformed
        List<Trajet> auxListe =new ArrayList<>();
        switch (critereRecherche.getSelectedItem()+"") {
                case "Adresse Depart":
                    for (Trajet listeTrajet1 : listeTrajets) {
                        if(listeTrajet1.getAdresseDep().equals(recherche.getText()))
                            auxListe.add(listeTrajet1);
                    }
                    jTable1.setModel(new ConsulterTrajets(auxListe));                    
                    break;
                case "Adresse Destination":
                    for (Trajet listeTrajet1 : listeTrajets) {
                        if(listeTrajet1.getAdresseDest().equals(recherche.getText()))
                            auxListe.add(listeTrajet1);
                    }
                    jTable1.setModel(new ConsulterTrajets(auxListe));                    
                    break;
                default:
                    recherche.setText("Erreur");
                    break;
            }
    }//GEN-LAST:event_rechercheButtonActionPerformed

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        Trajet t =new Trajet();
        
        // Client vide ou pas de Client
            Client c = new Client();
            c.setIdClient(0);
            c.setCin(0);
            c.setAdresse("adresse");
            c.setLogin("login");
            c.setNom("nom");
            c.setPrenom("prenom");
            c.setPwd("123456");
            c.setEmail("email");
            c.setTelephone(715592);
            
        t.setClient(c);
        t.setRespAgence(AccueilRespAgence.getRespAgence());
        t.setAdresseDep(adresseDep.getText());
        t.setAdresseDest(adresseDest.getText());
        t.setCout(0);
        t.setEtat(true);
        
        TrajetDAO.getInstance().insertTrajet(t);
        refresh();
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void modifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButtonActionPerformed
        try {
            Trajet t =new Trajet();
        
        // Client vide ou pas de Client
            Client c = new Client();
            c.setIdClient(0);
            c.setCin(0);
            c.setAdresse("adresse");
            c.setLogin("login");
            c.setNom("nom");
            c.setPrenom("prenom");
            c.setPwd("123456");
            c.setEmail("email");
            c.setTelephone(715592);
            
            t.setIdTrajet(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString()));
            t.setClient(ClientDAO.getInstance().findClientById(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString())));
            t.setRespAgence(AccueilRespAgence.getRespAgence());
            t.setAdresseDep(adresseDep.getText());
            t.setAdresseDest(adresseDest.getText());
            t.setCout(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),5).toString()));
            t.setEtat(true);
            
            TrajetDAO.getInstance().updateTrajet(t);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner une ligne" );
        }
    }//GEN-LAST:event_modifierButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        adresseDep.setText("");
        adresseDest.setText("");
        recherche.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTrajet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresseDep;
    private javax.swing.JTextField adresseDest;
    private javax.swing.JButton ajouterButton;
    private javax.swing.JComboBox critereRecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifierButton;
    private javax.swing.JTextField recherche;
    private javax.swing.JButton rechercheButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton retourButton;
    private javax.swing.JButton supprimerButton;
    // End of variables declaration//GEN-END:variables
}
