/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.gui.responsableagence;

import edu.esprit.DAO.classes.AgenceDAO;
import edu.esprit.DAO.classes.VoitureDAO;
import edu.esprit.adapters.ConsulterVoitures;
import edu.esprit.entities.Agence;
import edu.esprit.entities.Voiture;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Houssem
 */
public class GestionVoiture extends javax.swing.JFrame {

    /**
     * Creates new form GestionVoiture
     */
    
    private List<Agence> listeAgences = new ArrayList<>();
    private List<Voiture> listeVoitures = new ArrayList<>();
    
    public GestionVoiture() {
        initComponents();
        jTable1.setModel(new ConsulterVoitures());
        listeAgences=getListeAgence();
        setMyListBox();
    }
    
    private void updateModel(){
        
        jTable1.setModel(new ConsulterVoitures());
    }

    private List<Agence> getListeAgence() {
        
        AgenceDAO agenceDao = AgenceDAO.getInstance();
        return agenceDao.DisplayAllAgences();         
    }
    
    private void setMyListBox(){
        for (Agence a : listeAgences) {
            idagence.addItem(a.getNomAgence());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonAjouter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        typeVoiture = new javax.swing.JTextField();
        nbrPlace = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        matricule = new javax.swing.JTextField();
        idChauffeur = new javax.swing.JLabel();
        etatDispo = new javax.swing.JRadioButton();
        labelPrenom = new javax.swing.JLabel();
        etatNDispo = new javax.swing.JRadioButton();
        labelNom = new javax.swing.JLabel();
        idagence = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        ButtonUpdate = new javax.swing.JButton();
        ButtonSupprimer = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        retourButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ButtonAjouter.setText("Ajouter");
        ButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjouterActionPerformed(evt);
            }
        });

        jLabel2.setText("Etat");

        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });

        idChauffeur.setText("Matricule");

        etatDispo.setText("Disponible");
        etatDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etatDispoActionPerformed(evt);
            }
        });

        labelPrenom.setText("Type Voiture");

        etatNDispo.setText("Non Disponible");
        etatNDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etatNDispoActionPerformed(evt);
            }
        });

        labelNom.setText("Nombre de Place");

        jLabel1.setText("Agence");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNom)
                                .addGap(34, 34, 34)
                                .addComponent(nbrPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(typeVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idagence, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(etatNDispo)
                                                    .addComponent(etatDispo)))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrenom)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(idChauffeur))
                                .addGap(30, 30, 30)
                                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idChauffeur)
                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etatDispo)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idagence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etatNDispo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPrenom)
                        .addComponent(typeVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNom)
                    .addComponent(nbrPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        ButtonUpdate.setText("Modifier");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonSupprimer.setText("Supprimer");
        ButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSupprimerActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");

        retourButton.setText("Retour");
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retourButton)
                .addGap(18, 18, 18)
                .addComponent(ButtonReset)
                .addGap(56, 56, 56)
                .addComponent(ButtonSupprimer)
                .addGap(31, 31, 31)
                .addComponent(ButtonUpdate)
                .addGap(42, 42, 42)
                .addComponent(ButtonAjouter)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAjouter)
                    .addComponent(ButtonUpdate)
                    .addComponent(ButtonSupprimer)
                    .addComponent(ButtonReset)
                    .addComponent(retourButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        matricule.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0).toString());
        idagence.setSelectedItem(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),1).toString());
        nbrPlace.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),2).toString());
        typeVoiture.setText(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),3).toString());
        
        if ("false".equals(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),4).toString())){
            etatNDispo.setSelected(true);
            etatDispo.setSelected(false);
        }            
        else if ("true".equals(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),4).toString())){
            etatDispo.setSelected(true);
            etatNDispo.setSelected(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void ButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjouterActionPerformed

        Voiture v=new Voiture();
        v.setMatricule(matricule.getText());
        for (Agence a : listeAgences) {
            if(a.getNomAgence().equals(idagence.getSelectedItem())){
                v.setAgence(a);
                break;
            }        
        }
        if (etatDispo.isSelected())
            v.setEtat(true);
        else if (etatNDispo.isSelected())
            v.setEtat(false);
        
        v.setNbrPlace(Integer.parseInt(nbrPlace.getText()));
        v.setTypeVoiture(typeVoiture.getText());

        VoitureDAO vDAO =VoitureDAO.getInstance();
        vDAO.insertVoiture(v);

        updateModel();
    }//GEN-LAST:event_ButtonAjouterActionPerformed

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed

        Voiture v=new Voiture();
        v.setMatricule(matricule.getText());
                for (Agence a : listeAgences) {
            if(a.getNomAgence().equals(idagence.getSelectedItem())){
                v.setAgence(a);
                break;
            }        
        }
        
        if (etatDispo.isSelected())
            v.setEtat(true);
        else if (etatNDispo.isSelected())
            v.setEtat(false);
        v.setNbrPlace(Integer.parseInt(nbrPlace.getText()));
        v.setTypeVoiture(typeVoiture.getText());

        VoitureDAO.getInstance().updateVoiture(v);
        updateModel();
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void ButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSupprimerActionPerformed

        String id= jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0).toString();
        VoitureDAO.getInstance().deleteVoiture(id);
        updateModel();
    }//GEN-LAST:event_ButtonSupprimerActionPerformed

    private void etatNDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etatNDispoActionPerformed
        if (etatDispo.isSelected())
            etatDispo.setSelected(false);
    }//GEN-LAST:event_etatNDispoActionPerformed

    private void etatDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etatDispoActionPerformed
        if (etatNDispo.isSelected())
            etatNDispo.setSelected(false);
    }//GEN-LAST:event_etatDispoActionPerformed

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        AccueilRespAgence.getAccueilGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionVoiture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAjouter;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSupprimer;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JRadioButton etatDispo;
    private javax.swing.JRadioButton etatNDispo;
    private javax.swing.JLabel idChauffeur;
    private javax.swing.JComboBox idagence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JTextField matricule;
    private javax.swing.JTextField nbrPlace;
    private javax.swing.JButton retourButton;
    private javax.swing.JTextField typeVoiture;
    // End of variables declaration//GEN-END:variables
}
